server:
  port: 8081
  tomcat:
    max-connections: 60000  #tomcat的IO连接超时时长

mybatis:
  type-aliases-package: com.mall.api.entity    # 所有Entity别名类所在包
  mapper-locations:
  - classpath*:**/mapperxml/**/*.xml                       # mapper映射文件

spring:
  application:
    name: item-service
  datasource:
      url: jdbc:mysql://localhost:3308/universal_mall?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
      username: root
      password: myoa888
      driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone : http://127.0.0.1:10086/eureka/ #eureka服务注册地址
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1