
server:
  port: 9090

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/universal_mall?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
#      username: abc
#    password: abc123456
#    driver-class-name: com.mysql.jdbc.Driver


spring:
  datasource:
    url: jdbc:mysql://localhost:3308/universal_mall?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
      username: root
    password: myoa888
    driver-class-name: com.mysql.jdbc.Driver
