
server:
  port: 8011

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:10086/eureka/
  instance:
    instance-id: loginCustomer

spring:
  application:
    name: login-customer
  thymeleaf:
    prefix: classpath:/templates/

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false #关闭熔断器超时检测时间功能，也就是不超时






