
server:
  port: 8020

feign:
  hystrix:
    enabled: true

  datasource:
    url: jdbc:mysql://localhost:3308/universal_mall?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: myoa888
    driver-class-name: com.mysql.jdbc.Driver

